require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TuilesController do

  # This should return the minimal set of attributes required to create a valid
  # Tuile. As you add validations to Tuile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "lien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TuilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tuiles as @tuiles" do
      tuile = Tuile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tuiles).should eq([tuile])
    end
  end

  describe "GET show" do
    it "assigns the requested tuile as @tuile" do
      tuile = Tuile.create! valid_attributes
      get :show, {:id => tuile.to_param}, valid_session
      assigns(:tuile).should eq(tuile)
    end
  end

  describe "GET new" do
    it "assigns a new tuile as @tuile" do
      get :new, {}, valid_session
      assigns(:tuile).should be_a_new(Tuile)
    end
  end

  describe "GET edit" do
    it "assigns the requested tuile as @tuile" do
      tuile = Tuile.create! valid_attributes
      get :edit, {:id => tuile.to_param}, valid_session
      assigns(:tuile).should eq(tuile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tuile" do
        expect {
          post :create, {:tuile => valid_attributes}, valid_session
        }.to change(Tuile, :count).by(1)
      end

      it "assigns a newly created tuile as @tuile" do
        post :create, {:tuile => valid_attributes}, valid_session
        assigns(:tuile).should be_a(Tuile)
        assigns(:tuile).should be_persisted
      end

      it "redirects to the created tuile" do
        post :create, {:tuile => valid_attributes}, valid_session
        response.should redirect_to(Tuile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tuile as @tuile" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tuile.any_instance.stub(:save).and_return(false)
        post :create, {:tuile => { "lien" => "invalid value" }}, valid_session
        assigns(:tuile).should be_a_new(Tuile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tuile.any_instance.stub(:save).and_return(false)
        post :create, {:tuile => { "lien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tuile" do
        tuile = Tuile.create! valid_attributes
        # Assuming there are no other tuiles in the database, this
        # specifies that the Tuile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tuile.any_instance.should_receive(:update).with({ "lien" => "MyString" })
        put :update, {:id => tuile.to_param, :tuile => { "lien" => "MyString" }}, valid_session
      end

      it "assigns the requested tuile as @tuile" do
        tuile = Tuile.create! valid_attributes
        put :update, {:id => tuile.to_param, :tuile => valid_attributes}, valid_session
        assigns(:tuile).should eq(tuile)
      end

      it "redirects to the tuile" do
        tuile = Tuile.create! valid_attributes
        put :update, {:id => tuile.to_param, :tuile => valid_attributes}, valid_session
        response.should redirect_to(tuile)
      end
    end

    describe "with invalid params" do
      it "assigns the tuile as @tuile" do
        tuile = Tuile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tuile.any_instance.stub(:save).and_return(false)
        put :update, {:id => tuile.to_param, :tuile => { "lien" => "invalid value" }}, valid_session
        assigns(:tuile).should eq(tuile)
      end

      it "re-renders the 'edit' template" do
        tuile = Tuile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tuile.any_instance.stub(:save).and_return(false)
        put :update, {:id => tuile.to_param, :tuile => { "lien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tuile" do
      tuile = Tuile.create! valid_attributes
      expect {
        delete :destroy, {:id => tuile.to_param}, valid_session
      }.to change(Tuile, :count).by(-1)
    end

    it "redirects to the tuiles list" do
      tuile = Tuile.create! valid_attributes
      delete :destroy, {:id => tuile.to_param}, valid_session
      response.should redirect_to(tuiles_url)
    end
  end

end
